### ISSUE TITLE
下载证书报错

### ISSUE THREAD

**Issue by zhoutou123** [wechatpay-apiv3/CertificateDownloader#1]
```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.elias.CertificateDownloader@43b0ade): java.lang.IllegalArgumentException: java.security.InvalidKeyException: Illegal key size
	at picocli.CommandLine.executeUserObject(CommandLine.java:1738)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1928)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2282)
	at picocli.CommandLine.run(CommandLine.java:2740)
	at picocli.CommandLine.run(CommandLine.java:2677)
	at com.elias.CertificateDownloader.main(CertificateDownloader.java:155)
Caused by: java.lang.IllegalArgumentException: java.security.InvalidKeyException: Illegal key size
	at com.wechat.pay.contrib.apache.httpclient.util.AesUtil.decryptToString(AesUtil.java:42)
	at com.elias.CertificateDownloader.decryptAndValidate(CertificateDownloader.java:118)
	at com.elias.CertificateDownloader.downloadCertificate(CertificateDownloader.java:103)
	at com.elias.CertificateDownloader.run(CertificateDownloader.java:67)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	... 8 more
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at com.wechat.pay.contrib.apache.httpclient.util.AesUtil.decryptToString(AesUtil.java:35)
	... 12 more
```
apiV3key为32位字符串

**Comment by xy-peng** [comment]
看看[使用Java加载密钥时，抛出异常InvalidKeyException: Illegal key size](https://wechatpay-api.gitbook.io/wechatpay-api-v3/chang-jian-wen-ti/api-v3-mi-yao-xiang-guan#shi-yong-java-jia-zai-mi-yao-shi-pao-chu-yi-chang-invalidkeyexception-illegal-key-size)

**Comment by Gaoxu97** [comment]
![image](https://user-images.githubusercontent.com/104299708/164969593-b0d817d9-e5d1-4d00-8bde-a1bb44f85097.png)
这里也遇到了......
