### ISSUE TITLE
下载平台证书出错

### ISSUE THREAD

**Issue by newPepole123** [wechatpay-apiv3/CertificateDownloader#10]
报错：=== download begin ===
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.elias.CertificateDownloader@18ef96): java.lang.IllegalArgumentException: Illegal base64 character 2d
        at picocli.CommandLine.executeUserObject(CommandLine.java:1738)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1928)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2282)
        at picocli.CommandLine.run(CommandLine.java:2740)
        at picocli.CommandLine.run(CommandLine.java:2677)
        at com.elias.CertificateDownloader.main(CertificateDownloader.java:129)
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 2d
        at java.util.Base64$Decoder.decode0(Unknown Source)
        at java.util.Base64$Decoder.decode(Unknown Source)
        at java.util.Base64$Decoder.decode(Unknown Source)
        at com.wechat.pay.contrib.apache.httpclient.util.PemUtil.loadPrivateKey(PemUtil.java:36)
        at com.elias.CertificateDownloader.downloadCertificate(CertificateDownloader.java:55)
        at com.elias.CertificateDownloader.run(CertificateDownloader.java:105)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
        ... 8 more

**Comment by xy-peng** [comment]
看栈信息，可能是商户证书私钥文件的问题，你检查下`-f`传入的商户证书文件，要是apiclient_key.pem的原始文件

**Comment by puzzle9** [comment]
我也遇到了这个问题 
他 -f 传递的是 apiclient_key.pem

**Comment by jk030611** [comment]
![1637075487(1)](https://user-images.githubusercontent.com/90101046/142011400-1a59a1b0-3201-48e9-a898-e42153cef4c9.png)
我也不行， 这个要怎么解决

**Comment by jk030611** [comment]
> 我也遇到了这个问题 我 -f 传递的是 apiclient_key.pem 后正常了

可以把完整的命令示例截图看下不？ 关键信息可以不用完整

**Comment by puzzle9** [comment]
> > 我也遇到了这个问题 我 -f 传递的是 apiclient_key.pem 后正常了
> 
> 可以把完整的命令示例截图看下不？ 关键信息可以不用完整

你这个 应该还没到这一步

看着错误 或许是参数的那个文件没传对

**Comment by jk030611** [comment]
目前我还成普通商户调用是可以了，特约商户的资料还在申请，后面有问题再麻烦你帮忙看看，多谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: puz_zle ***@***.***&gt;
发送时间: 2021年11月17日 14:23
收件人: wechatpay-apiv3/CertificateDownloader ***@***.***&gt;
抄送: jk030611 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[wechatpay-apiv3/CertificateDownloader] 下载平台证书出错 (#10)





   
我也遇到了这个问题 我 -f 传递的是 apiclient_key.pem 后正常了
  
可以把完整的命令示例截图看下不？ 关键信息可以不用完整
  
你这个 应该还没到这一步
 
看着错误 或许是参数的那个文件没传对
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
