### ISSUE TITLE
下载证书报错无效的密钥格式

### ISSUE THREAD

**Issue by bnyte** [wechatpay-apiv3/CertificateDownloader#12]
指令：`java -jar CertificateDownloader-1.1.jar -k ** -m ** -f /apiclient_key.pem -s ** -o .`

日志信息：

```
=== download begin ===
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.elias.CertificateDownloader@5f150435): java.lang.RuntimeException: 无效的密钥格式
	at picocli.CommandLine.executeUserObject(CommandLine.java:1738)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1928)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2282)
	at picocli.CommandLine.run(CommandLine.java:2740)
	at picocli.CommandLine.run(CommandLine.java:2677)
	at com.elias.CertificateDownloader.main(CertificateDownloader.java:155)
Caused by: java.lang.RuntimeException: 无效的密钥格式
	at com.wechat.pay.contrib.apache.httpclient.util.PemUtil.loadPrivateKey(PemUtil.java:40)
	at com.elias.CertificateDownloader.downloadCertificate(CertificateDownloader.java:82)
	at com.elias.CertificateDownloader.run(CertificateDownloader.java:67)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	... 8 more
```

**Comment by xy-peng** [comment]
> Caused by: java.lang.RuntimeException: 无效的密钥格式

私钥文件对吗？

**Comment by bnyte** [comment]
忘了啥问题了 后来改解决方案了 如果有相同问题再次打开
