### ISSUE TITLE
证书下载失败

### ISSUE THREAD

**Issue by aroundsm** [wechatpay-apiv3/CertificateDownloader#5]
=== download begin ===
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.elias.CertificateDownloader@6956de9): java.lang.IllegalArgumentException: Illegal base64 character 3f
        at picocli.CommandLine.executeUserObject(CommandLine.java:1738)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1928)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2282)
        at picocli.CommandLine.run(CommandLine.java:2740)
        at picocli.CommandLine.run(CommandLine.java:2677)
        at com.elias.CertificateDownloader.main(CertificateDownloader.java:155)
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 3f
        at java.util.Base64$Decoder.decode0(Base64.java:714)
        at java.util.Base64$Decoder.decode(Base64.java:526)
        at java.util.Base64$Decoder.decode(Base64.java:549)
        at com.wechat.pay.contrib.apache.httpclient.util.PemUtil.loadPrivateKey(PemUtil.java:36)
        at com.elias.CertificateDownloader.downloadCertificate(CertificateDownloader.java:82)
        at com.elias.CertificateDownloader.run(CertificateDownloader.java:67)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
        ... 8 more

**Comment by aroundsm** [comment]
使用apiclient_key.pem

**Comment by bofale** [comment]
> 
apiclient_key.pem 这个是商户api v3 私钥文件是吗
